[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking = "HTZ275L8mFESgZSXo4b3EJAp45fgchDkrZEw8fY2UK8x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/victorcarvalho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
